// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNUoaYe0dCegRRjjHSjU1C46iqujUExTI',
    appId: '1:1045965580557:web:bd1a49a01e08fdfc132844',
    messagingSenderId: '1045965580557',
    projectId: 'auth-f876b',
    authDomain: 'auth-f876b.firebaseapp.com',
    storageBucket: 'auth-f876b.appspot.com',
    measurementId: 'G-BB1WKQVDGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUp85PLCl71Nz6z_xhsttyAGhyC7HM8v8',
    appId: '1:1045965580557:android:a6499fdd82255093132844',
    messagingSenderId: '1045965580557',
    projectId: 'auth-f876b',
    storageBucket: 'auth-f876b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-3CTzAa4ZF53UgUpH_97p5bv1ep1_kA',
    appId: '1:1045965580557:ios:6ea0217baa15ee69132844',
    messagingSenderId: '1045965580557',
    projectId: 'auth-f876b',
    storageBucket: 'auth-f876b.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY-3CTzAa4ZF53UgUpH_97p5bv1ep1_kA',
    appId: '1:1045965580557:ios:dab7454280bad1b6132844',
    messagingSenderId: '1045965580557',
    projectId: 'auth-f876b',
    storageBucket: 'auth-f876b.appspot.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
